### ISSUE TITLE
Leaflet component

### ISSUE THREAD

**Issue by HansKallekleiv** [equinor/webviz-subsurface-components#110]
Layer types:

- [ ] TileLayer - Locally served tiles using flask route or base64 transfer?)

- [ ] Performant ImageLayer for fast flipping through images

- [ ] GL based Tile/Image layers with mouse readout and **manipulation of z-value** (e.g. difference between two maps)

- [ ] Well trajectories (simple lines)

- [ ] Well logs using d3.js / pixi.js activated at specific zoom level 
https://github.com/manubb/Leaflet.PixiOverlay

- [ ] Fault polygons, etc

- [ ] Client side selection of colormap.

Data input:

- [ ] Performant image generation from surfaces (python)

- [ ] Performant tile generation from images (python)

Interactivity:
- Draw polylines, polygons and points on a map

**Comment by anders-kiaer** [comment]
Sounds good! 🎉🚀  I guess we might want to collaborate on that same PR #109, when people have time (**cc** @anders-kiaer, @HansKallekleiv, @thor85 ++) - we can always go back some commits if we decide on going a different route.

Since this is a big issue - we can maybe put our name behind each of the subtasks when self-assigning something, such that we don't work on the same item simultaneously.

**Comment by HansKallekleiv** [comment]
Good plan. Also feel free to add any tasks / ideas to this issue. The list above is far from complete.

**Comment by thor85** [comment]
I tried looking into tile generation/serving. No conclusion, but posting some links you can check out.

- [GDAL](https://gdal.org/) which Troll maps are using works good for pre-generating tiles and reading them from disk.
- Looks like [TileMill](https://tilemill-project.github.io/tilemill) \([github](https://github.com/tilemill-project)\) can generate tiles in [MBTiles format](https://github.com/mapbox/mbtiles-spec), but seems like that maybe also uses [GDAL](https://tilemill-project.github.io/tilemill/docs/guides/gdal/)?.
- [Leaflet.TileLayer.MBTiles](https://gitlab.com/IvanSanchez/Leaflet.TileLayer.MBTiles) can display MBTiles in Leaflet (only raster tiles).
- [Tilelive](https://github.com/tilemill-project/tilelive) Fast interface to tiles with pluggable backends
- [TileCache](http://tilecache.org/)
- [TileStache](http://tilestache.org/)
- [TileStream](https://github.com/cutting-room-floor/tilestream)
- [MapTiler](https://www.maptiler.com/)
- [TileCloud Chain](https://github.com/camptocamp/tilecloud-chain)
- [PGRestAPI](https://github.com/spatialdev/PGRestAPI)
- [TileServer GL](https://github.com/maptiler/tileserver-gl)

[Vector tiles](https://github.com/mapbox/vector-tile-spec) is probably not the solution for surfaces, but could maybe be used for other data, e.g. cylinder logs?
- [mapbox-vector-tile](https://github.com/tilezen/mapbox-vector-tile)
- [geojson-vt](https://github.com/mapbox/geojson-vt) Create vector tiles on-the-fly without a server. [Explanation](https://blog.mapbox.com/rendering-big-geodata-on-the-fly-with-geojson-vt-4e4d2a5dd1f2)
- [Leaflet.VectorTileLayer](https://gitlab.com/jkuebart/Leaflet.VectorTileLayer/) Slice GeoJSON/TopoJSON into vector tiles or display vector tiles hosted and transferred with [protobuf](https://github.com/protocolbuffers/protobuf). Seems like it does not work with MBTiles format [yet](https://github.com/Leaflet/Leaflet.VectorGrid/issues/54).
- [Mapbox GL Leaflet](https://github.com/mapbox/mapbox-gl-leaflet) WebGL layer for vector tiles.

**Comment by ashildskalnes** [comment]
I would also like to have an option to print a well name along a well (not only as tooltip)

**Comment by thor85** [comment]
> I would also like to have an option to print a well name along a well (not only as tooltip)

Currently I show wellnames on a tileLayer in Troll Maps, but I have made a branch where I display names as svg. It was noticeably slower on Troll with so many wellbores, so I left it for a while untill I have time to look at a different option (maybe pixiJS?). Svg probably works fine for most fields with much less wells though.

**Comment by ashildskalnes** [comment]
Correct colormap scaling given min-/max values (both for map values inside or outside given min/max)

**Comment by ashildskalnes** [comment]
Possibility to change the map without having to add the well layers again

**Comment by asnyv** [comment]
Should have an option for logarithmic colormap (e.g. for permeability)

**Comment by anders-kiaer** [comment]
This is a summary of feature requests that is aimed for being included in the Dash `LayeredMap` component ("version 2") - which will replace and improve the existing `LayeredMap` component.

The existing component can be viewed in action in the [live demo](https://webviz-subsurface-example.azurewebsites.net/) on e.g. pages "Surface with seismic cross-section" (which shows how the user can draw a line, update the component state, and use Dash callbacks to update another Dash component) and "Surface viewer (FMU)" (which shows usage of syncing different instances of the same component).

It can be assumed that the data to be visualized is available locally on disk, and available to the Python instance running.

**Existing features that should probably be kept in some way:**
- Possibility for the Python user to send map data in some efficient format, appearing in different layers in the map.
- Possibility for the Python user to send overlays (lines, polygons, circles etc.) with tooltips.
- Possibility for the Python user to say that some given instances should sync zoom/pan.
- Possibility for the Python user to allow the client/browser user to scale the y axis (e.g. if the visualized data is not a map, but seismic intersection).
- Possibility for the Python user to allow the client/browser user to turn on/off hill shading.*
- Possibility for the Python user to allow the client/browser user to draw line/polygon or place a circle. The Python user can then use this state as input to further Dash callbacks.

* We have some simple hill shading implemented in the current version using WebGL. This could be improved (see [this](https://wwwtyro.net/2019/03/21/advanced-map-shading.html) and [this](https://www.esri.com/arcgis-blog/products/arcgis-living-atlas/imagery/introducing-esris-next-generation-hillshade/) reference for inspiration).

**Improvements to existing features / new features:**
- Might be better to work directly on https://leafletjs.com/ compared with the currently used https://react-leaflet.js.org/ (and instead do the top React wrapping towards the Dash component building ourselves).
- `xy` position and value of map indicated on hover.
- Show colorscales of selected maps.
- Possibility to do client side selection of used colormap (using e.g. Plotly's own [colorscale](https://plotly.github.io/react-colorscales/) React component).
- Possibility to have logarithmic colormap.
- Possibility to set cut-off points on colormap (i.e. that all values below/above cut-off has same color).
- Currently if any of the visualized data is updated, all the visualized data needs to be sent again from server to client. Only send changed data.
- Currently only "static" data is supported, which do not scale to big data sets/maps. Investigate usage of tile server (preferably served by Flask to be within the same software stack as Dash). Efficient creation of the tiles is not within scope of the project. Can e.g. assume they are premade and available on disk, and then maybe use something along the lines of this concept:

```python
from flask import Flask

app = Flask(__name__)

@app.route("/tiles/<zoom>/<y>/<x>")
def tiles(zoom, y, x):
    return send_file(f"./sometile{zoom}_{x}_{y}.png")

if __name__ == "__main__":
    app.run(debug=False, host="localhost", port=8080)
```

**Comment by anders-kiaer** [comment]
A bit more explanation on the "logarithmic colormap" and "cut-of points" on colormap.

* The Python user of the component should be able to choose between linear and logarithmic scale (default linear).
* The Python user should be able to set end-points of the colormap (default could be min-max of input data).
  * If user provides a colormap min/max end point that is higher/lower than global min/max in the map data, could show a ≤/≥ to indicate that the end point of the colormap is used as a "cut-off".
  * If user provides a colormap min/max end point that is lower/higher than global min/max in the map data, the effect is simply a larger range of the colormap.

A rouch sketch of linear/logarithmic in MS Paint 😎 🎨 
![image](https://user-images.githubusercontent.com/31612826/85009698-2b055280-b15f-11ea-9966-3f3f8e330481.png)

**Comment by anders-kiaer** [comment]
Implemented in #219. Let us move any remaining missing/wanted feature requests to separate issues.
