### ISSUE TITLE
Section view for SubsurfaceViewer component

### ISSUE THREAD

**Issue by hkfb** [equinor/webviz-subsurface-components#1956]
Create a new type of orthogonal view, using a custom deck.gl Viewport, that projects data in section (unfolded) coordinates, ie. [abscissa, Z].

![image](https://github.com/equinor/webviz-subsurface-components/assets/19621822/d0c63c6a-42c0-44a6-8778-7587908129d8)

See also https://github.com/equinor/webviz-subsurface-components/wiki/Intersection-component

### Bugs
- [x] #1957
### Refactoring
- [x] Dedicated view type for Sections (based on Orthographic)
- [x] #1968

###  Data layers
- [ ] 3D property sections unfolded (orthographic) and in 3D
- [x] #2019
- [ ] Horizon sections
- [ ] Horizon ensemble sections
- [ ] Well log projection
- [ ] Seismic sections

### Readout
- [ ] 3D property section readout
- [ ] 3D property I, J, K readout
- [ ] Section X, Y, Z, abscissa readout

### Camera control / linking
- [ ] Section viewport bounds control

### Cursor control / linking
- [ ] Display global cursor in section view
